/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Smauf
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
      this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txt_usuario = new javax.swing.JTextField();
        Jpass_Contras = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bttn_resgistroLogin = new javax.swing.JButton();
        bttn_inciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 190, 30));
        jPanel4.add(Jpass_Contras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("LOGIN");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 90, 40));

        jLabel2.setText("CONTRASEÑA");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel3.setText("USUARIO");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        bttn_resgistroLogin.setText("REGISTRAR");
        bttn_resgistroLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttn_resgistroLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_resgistroLoginActionPerformed(evt);
            }
        });
        jPanel4.add(bttn_resgistroLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 140, -1));

        bttn_inciar.setBackground(new java.awt.Color(0, 255, 255));
        bttn_inciar.setText("INICIAR SECCION");
        bttn_inciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttn_inciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_inciarActionPerformed(evt);
            }
        });
        jPanel4.add(bttn_inciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void bttn_resgistroLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_resgistroLoginActionPerformed
        this.setVisible(false);
        RegistroCliente r = new RegistroCliente();
        r.setVisible(true);
    }//GEN-LAST:event_bttn_resgistroLoginActionPerformed

    private void bttn_inciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_inciarActionPerformed
        this.setVisible(false);
        Housex r = new Housex();
        r.setVisible(true);
    }//GEN-LAST:event_bttn_inciarActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Jpass_Contras;
    private javax.swing.JButton bttn_inciar;
    private javax.swing.JButton bttn_resgistroLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
