/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import Logica.cls_cliente;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/**
 *
 * @author Smauf
 */
public class RegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCliente
     */
    public RegistroCliente() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bttn_volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_confirmar_contraseña = new javax.swing.JPasswordField();
        txt_correos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JPasswordField();
        txt_tarjeta_credito = new javax.swing.JTextField();
        bttn_registrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Formulario de Registro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 250, 20));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel4.setText("Telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel5.setText("Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        bttn_volver.setBackground(new java.awt.Color(153, 153, 153));
        bttn_volver.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        bttn_volver.setText("Volver");
        bttn_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(bttn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 30));

        jLabel6.setText("Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));
        jPanel1.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, -1));
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, -1));
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 170, -1));
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 170, -1));

        jLabel7.setText("Correo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        jPanel1.add(txt_confirmar_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 160, -1));
        jPanel1.add(txt_correos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, -1));

        jLabel8.setText("Tarjeta Credito:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel9.setText("Confirmar Contraseña:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 120, -1));
        jPanel1.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 170, -1));
        jPanel1.add(txt_tarjeta_credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 170, -1));

        bttn_registrar.setBackground(new java.awt.Color(0, 204, 255));
        bttn_registrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        bttn_registrar.setText("Registrar");
        bttn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(bttn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 130, 30));

        jLabel10.setText("Direccion:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_volverActionPerformed
          this.setVisible(false);
          Login r = new Login();
          r.setVisible(true);
    }//GEN-LAST:event_bttn_volverActionPerformed

    private void bttn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_registrarActionPerformed
        String nombre, usuario, clave, email, direccion,apellido, comfirmarclave;
        int tarjeta, telefono;
        
        nombre = txt_nombres.getText();
        apellido = txt_apellido.getText();
        usuario = txt_usuario.getText();
        clave = String.valueOf(txt_clave.getPassword());
        comfirmarclave = String.valueOf(txt_confirmar_contraseña.getPassword());
        email = txt_correos.getText();
        direccion = txt_direccion.getText();
        tarjeta = Integer.parseInt(txt_tarjeta_credito.getText());
        telefono = Integer.parseInt(txt_telefono.getText());
        
        cls_cliente c = new cls_cliente(nombre, usuario, clave, email, direccion,tarjeta, telefono,apellido,comfirmarclave );
        
    }//GEN-LAST:event_bttn_registrarActionPerformed

    public RegistroCliente(JPasswordField txt_clave, JTextField txt_correos, JTextField txt_direccion, JTextField txt_nombres, JTextField txt_tarjeta_credito, JTextField txt_usuario) {
        this.txt_clave = txt_clave;
        this.txt_correos = txt_correos;
        this.txt_direccion = txt_direccion;
        this.txt_nombres = txt_nombres;
        this.txt_tarjeta_credito = txt_tarjeta_credito;
        this.txt_usuario = txt_usuario;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_registrar;
    private javax.swing.JButton bttn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JPasswordField txt_confirmar_contraseña;
    private javax.swing.JTextField txt_correos;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_tarjeta_credito;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
